m

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,22 +1,10 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/configuration-reference
 version: 2.1
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
 jobs:
   say-hello:
-    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
     docker:
-      # Specify the version you desire here
-      # See: https://circleci.com/developer/images/image/cimg/base
       - image: cimg/base:current
-
-    # Add steps to the job
-    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
     steps:
-      # Checkout the code as the first step.
       - checkout
       - run:
           name: "Say hello"
@@ -24,24 +12,30 @@ jobs:
 
   build-docker-image:
     docker:
-      - image: docker:20.10.24 # Utilisation d'une image Docker officielle
+      - image: docker:20.10.24
     steps:
       - checkout
-      - setup_remote_docker: # Active le support de Docker
+      - setup_remote_docker:
           version: 20.10.24
       - run:
-          name: "check docker"
-          command: "[ -f dockerfile ] && echo 'Dockerfile found' || (echo 'Dockerfile missing' && exit 1) 
-          docker build -t myapp:latest .
-          docker run --rm -d -p 8080:8080 --name test-container mnoapp:latest
-          sleep 5
-          curl -i http://localhost:8080 || (echo "not started" && exit 1)""
+          name: "Check Dockerfile existence"
+          command: |
+            if [ ! -f Dockerfile ]; then
+              echo "Dockerfile missing" && exit 1
+            fi
+            echo "Dockerfile found"
+      - run:
+          name: "Build Docker Image"
+          command: "docker build -t myapp:latest ."
+      - run:
+          name: "Run and Test Container"
+          command: |
+            docker run --rm -d -p 8080:8080 --name test-container myapp:latest
+            sleep 5
+            curl -i http://localhost:8080 || (echo "Application not started" && exit 1)
 
-# Orchestrate jobs using workflows
-# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
 workflows:
-  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
-    # Inside the workflow, you define the jobs you want to run.
+  say-hello-workflow:
     jobs:
       - say-hello
       - build-docker-image
